# Generated by Django 5.1 on 2024-08-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
